const API=(window.TRIPON_ADMIN_API_BASE||'').replace(/\/$/,''),KEY='tripon_admin_session_token',$=s=>document.querySelector(s);
let editingPromotion=null,pendingCommand=null,promotions=[];
const pcs=[{id:'pc-1',name:'AI PC 01',role:'Gemma 주 처리',online:false,acceptRequests:true},{id:'pc-2',name:'AI PC 02',role:'실시간 상태 대기',online:false,acceptRequests:true}];
const esc=v=>String(v??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function api(path,options={}){const headers=new Headers(options.headers||{}),token=sessionStorage.getItem(KEY);if(token)headers.set('Authorization','Bearer '+token);const response=await fetch(API+path,{...options,headers,credentials:'include'});if(response.status===401)throw Error('AUTH');if(!response.ok){const payload=await response.json().catch(()=>({}));throw Error((payload.error||'REQUEST_FAILED')+(payload.upstreamStatus?' ('+payload.upstreamStatus+')':''))}return response.status===204?null:response.json()}
function table(headers,rows){return '<table class="table"><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table>'}
function renderOverview(){const online=pcs.filter(p=>p.online),requests=online.reduce((sum,p)=>sum+(p.requests||0),0),latencies=online.map(p=>p.daily).filter(Number.isFinite),average=latencies.length?Math.round(latencies.reduce((a,b)=>a+b,0)/latencies.length):null;$('#metricRequests').textContent=online.length?requests.toLocaleString('ko-KR'):'—';$('#metricAvg').textContent=average===null?'—':(average/1000).toFixed(2)+'초';$('#metricServers').innerHTML=online.length+' <em>/ 2</em>';$('#metricServerNote').innerHTML=online.length===2?'<b>정상</b> 모든 서버 연결':online.length+'대 연결';$('#overviewServers').innerHTML=pcs.map(p=>'<div class="mini-server"><div><strong>'+esc(p.name)+'</strong><small>'+esc(p.role)+' · 마지막 응답 '+esc(p.last||'기록 없음')+'</small></div><b>CPU '+metric(p.cpu,'%')+'</b><b>GPU '+metric(p.gpu,'%')+'</b><b>RAM '+metric(p.ram,'%')+'</b></div>').join('')}
function renderPromotions(){const rows=promotions.length?promotions.map(p=>'<tr><td><b>'+esc(p.code)+'</b></td><td><span class="tag">'+p.plan+'</span></td><td>'+(p.people?p.used+' / '+p.people:'제한 없음')+'</td><td>'+(p.date||'제한 없음')+'</td><td><button class="button edit" data-id="'+p.id+'">수정</button></td></tr>').join(''):'<tr><td colspan="5">아직 생성한 프로모션 코드가 없습니다.</td></tr>';$('#promoList').innerHTML=table(['코드','플랜','사용 인원','유효 기간',''],rows);document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openPromotion(promotions.find(p=>p.id===b.dataset.id)))}
async function loadPromotions(){try{const result=await api('/api/promotions');promotions=result.promotions||[];renderPromotions()}catch{$('#promoList').innerHTML='<p class="muted">프로모션 코드를 불러오지 못했습니다. 새로고침해 주세요.</p>'}}
function fmtLast(value){if(!value)return '기록 없음';const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));return seconds<60?'방금 전':seconds<3600?Math.floor(seconds/60)+'분 전':seconds<86400?Math.floor(seconds/3600)+'시간 전':new Date(value).toLocaleString('ko-KR')}
function metric(value,suffix=''){return value===null||value===undefined?'—':String(value)+suffix}
function renderAI(){const online=pcs.filter(p=>p.online);$('#serverCount').innerHTML='<i></i> '+online.length+'대 연결됨';$('#serverGrid').innerHTML=pcs.map(p=>'<article class="server"><div class="server-top"><div><h3>'+esc(p.name)+'</h3><p>'+esc(p.role)+' · 마지막 응답 '+esc(p.last||'기록 없음')+'</p></div><span class="badge '+(p.online?'':'offline')+'"><i></i> '+(p.online?'온라인':'연결 안 됨')+'</span></div><div class="request-routing"><div><b>AI 요청 수신</b><small>'+(p.acceptRequests?'이 PC가 새 AI 요청을 받을 수 있습니다.':'새 AI 요청에서 제외됩니다.')+'</small></div><button class="route-toggle '+(p.acceptRequests?'on':'off')+'" data-id="'+p.id+'" data-enabled="'+p.acceptRequests+'" aria-pressed="'+p.acceptRequests+'">'+(p.acceptRequests?'받는 중':'중지됨')+'</button></div><div class="server-metrics">'+[['CPU',metric(p.cpu,'%')],['GPU',metric(p.gpu,'%')],['RAM',metric(p.ram,'%')],['GPU 온도',metric(p.temp,'°C')],['일간 평균',metric(p.daily,' ms')],['월간 평균',metric(p.monthly,' ms')]].map(x=>'<div class="metric"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')+'</div><div class="server-actions"><button class="button cmd" data-id="'+p.id+'" data-action="restart" '+(p.online?'':'disabled')+'>다시 시작</button><button class="danger cmd" data-id="'+p.id+'" data-action="shutdown" '+(p.online?'':'disabled')+'>PC 종료</button></div></article>').join('');document.querySelectorAll('.cmd:not(:disabled)').forEach(b=>b.onclick=()=>openControl(b.dataset.id,b.dataset.action));document.querySelectorAll('.route-toggle').forEach(b=>b.onclick=()=>setAcceptRequests(b.dataset.id,b.dataset.enabled!=='true'));$('#periods').innerHTML=[['일간 평균','daily'],['주간 평균','weekly'],['월간 평균','monthly']].map(([label,key])=>{const rows=online.map(p=>p[key]).filter(Number.isFinite);const average=rows.length?Math.round(rows.reduce((a,b)=>a+b,0)/rows.length):null;return '<div class="period"><span>'+label+'</span><b>'+metric(average,' ms')+'</b></div>'}).join('')}
async function loadServers(){try{const result=await api('/api/servers'),servers=Array.isArray(result.servers)?result.servers:[];for(const p of pcs){const s=servers.find(x=>x.serverId===p.id);if(!s){p.online=false;continue}Object.assign(p,{name:s.name||(p.id==='pc-1'?'AI PC 01':'AI PC 02'),role:(p.id==='pc-1'?'PC 01':'PC 02')+' · '+(s.model||'로컬 Gemma')+' · 실시간 수집',online:s.online===true,acceptRequests:s.acceptRequests!==false,cpu:s.cpu,gpu:s.gpu,ram:s.ram,temp:s.gpuTempC,last:fmtLast(s.lastSeenAt||s.lastAiResponseAt),daily:s.averageLatencyMs?.daily,weekly:s.averageLatencyMs?.weekly,monthly:s.averageLatencyMs?.monthly,requests:s.requests?.completed||0})}}catch(error){for(const p of pcs){p.online=false;p.role='실시간 상태 오류 · '+(error.message||'요청 실패')}}renderAI();renderOverview()}
async function setAcceptRequests(id,acceptRequests){const pc=pcs.find(p=>p.id===id);if(!pc)return;const previous=pc.acceptRequests;pc.acceptRequests=acceptRequests;renderAI();try{await api('/api/servers/'+encodeURIComponent(id)+'/accept-requests',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({acceptRequests})});await loadServers()}catch(error){pc.acceptRequests=previous;renderAI();alert('AI 요청 수신 설정을 저장하지 못했습니다. '+(error.message||'다시 시도해 주세요.'))}}
function renderUsers(){const users=[['김여행','카카오','traveler@tripon.app','Pro'],['이하늘','Google','—','Free'],['Alex Kim','Apple','alex@example.com','Enterprise']];$('#userList').innerHTML=table(['사용자 이름','로그인 방법','이메일','플랜'],users.map(u=>'<tr><td><b>'+u[0]+'</b></td><td>'+u[1]+'</td><td>'+u[2]+'</td><td><span class="tag">'+u[3]+'</span></td></tr>').join(''))}
function render(){renderOverview();renderAI();renderUsers();loadPromotions();loadServers()}
function openPromotion(p){editingPromotion=p||null;$('#promoTitle').textContent=p?'프로모션 코드 수정':'프로모션 코드 생성';$('#code').value=p?.code||'';$('#plan').value=p?.plan||'Pro';$('#peopleOn').checked=Boolean(p?.people);$('#people').value=p?.people||100;$('#dateOn').checked=Boolean(p?.date);$('#date').value=p?.date||'';toggleLimits();$('#promoDialog').showModal()}
function toggleLimits(){$('#peopleBox').hidden=!$('#peopleOn').checked;$('#dateBox').hidden=!$('#dateOn').checked}
function openControl(id,action){pendingCommand={id,action};$('#controlTitle').textContent=action==='shutdown'?'PC 종료 명령 확인':'PC 다시 시작 명령 확인';$('#controlText').textContent=id+'에 '+(action==='shutdown'?'종료':'다시 시작')+' 명령을 전송합니다. 진행 중인 AI 요청이 중단될 수 있습니다.';$('#confirm').checked=false;$('#controlError').textContent='';$('#controlDialog').showModal()}
function showApp(){$('#loginView').hidden=true;$('#dashboardView').hidden=false;render()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);try{const r=await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:form.get('id'),password:form.get('password')})});sessionStorage.setItem(KEY,r.token);showApp()}catch{$('#loginError').textContent='관리자 ID 또는 비밀번호를 확인해 주세요.'}};
$('#logoutBtn').onclick=async()=>{try{await api('/api/admin/logout',{method:'POST'})}catch{}sessionStorage.removeItem(KEY);location.reload()};
$('#refreshBtn').onclick=()=>{render();$('#modeBadge').innerHTML='<i></i> 방금 동기화됨'};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{const id=b.dataset.tab;document.querySelectorAll('.nav,.tab').forEach(x=>x.classList.remove('active'));document.querySelector('.nav[data-tab="'+id+'"]').classList.add('active');$('#'+id).classList.add('active');$('#pageTitle').textContent=b.textContent.replace('→','').trim()});
$('#newPromo').onclick=()=>openPromotion();$('#peopleOn').onchange=toggleLimits;$('#dateOn').onchange=toggleLimits;
$('#promoForm').onsubmit=async e=>{e.preventDefault();const payload={code:$('#code').value.trim(),plan:$('#plan').value,people:$('#peopleOn').checked?Number($('#people').value):null,date:$('#dateOn').checked?$('#date').value:null};try{await api(editingPromotion?'/api/promotions/'+editingPromotion.id:'/api/promotions',{method:editingPromotion?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#promoDialog').close();await loadPromotions()}catch(error){alert(error.message==='DUPLICATE_CODE'?'이미 사용 중인 프로모션 코드입니다.':'프로모션 코드를 저장하지 못했습니다.')}};
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#controlForm').onsubmit=async e=>{e.preventDefault();if(!$('#confirm').checked){$('#controlError').textContent='명령 실행 영향을 확인해 주세요.';return}try{await api('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({serverId:pendingCommand.id,action:pendingCommand.action==='restart'?'restart_pc':'shutdown'})});$('#controlDialog').close()}catch{$('#controlError').textContent='명령 전송에 실패했습니다. 제어 에이전트 연결을 확인해 주세요.'}};
api('/api/admin/session').then(showApp).catch(()=>{});setInterval(()=>{if(!$('#dashboardView').hidden)loadServers()},5000);
